# name: Update Publications from Google Scholar

# on:
#   # Run on push to main branch
#   push:
#     branches: [main, master]

#   # Run on pull request
#   pull_request:
#     branches: [main, master]

#   # Allow manual trigger
#   workflow_dispatch:

#   # Run weekly to catch new publications
#   schedule:
#     - cron: "0 0 * * 0" # Every Sunday at midnight UTC

# jobs:
#   update-publications:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           fetch-depth: 0

#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.12"

#       - name: Install Python dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install requests beautifulsoup4

#       - name: Update publications
#         run: |
#           cd ${{ github.workspace }}
#           python _scripts/update_publications.py

#       - name: Check for changes
#         id: verify-changed-files
#         run: |
#           if [ -n "$(git status --porcelain)" ]; then
#             echo "changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "changed=false" >> $GITHUB_OUTPUT
#           fi

#       - name: Commit changes
#         if: steps.verify-changed-files.outputs.changed == 'true'
#         run: |
#           git config --local user.email "action@github.com"
#           git config --local user.name "GitHub Action"
#           git add _bibliography/papers.bib
#           git commit -m "Auto-update publications from Google Scholar [skip ci]" || exit 0

#       - name: Push changes
#         if: steps.verify-changed-files.outputs.changed == 'true'
#         uses: ad-m/github-push-action@master
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: ${{ github.ref }}

#   build-and-deploy:
#     needs: update-publications
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4
#         with:
#           ref: ${{ github.ref }}

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: ">= 3.3.6"
#           bundler-cache: true

#       - name: Install dependencies
#         run: |
#           bundle install

#       - name: Build site
#         run: |
#           bundle exec jekyll build

#       - name: Deploy to GitHub Pages
#         if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./_site
